### ISSUE TITLE
How I reproduce the pretraining from scratch.

### ISSUE THREAD

**Issue by Tokenmw** [moment-timeseries-foundation-model/moment-research#11]
Hi, I wanna to do pretraining from scratch. I am not sure whether I can use provided pretrain.yaml configure to directly run pretraining? This provided parameters is the same as paper? Thank you so much.

**Comment by mononitogoswami** [comment]
Hi, 
Yes, you should be able to use the hyper-parameters in pretrain.yaml and the pre-training scripts (https://github.com/moment-timeseries-foundation-model/moment-research/blob/main/scripts/pretraining/pretraining.py) to pre-train models from scratch. The pre-training data (the Time Series Pile) is available [here](https://huggingface.co/AutonLab).

Best,
Mononito

**Comment by lixus7** [comment]
你好，Gong博。我看到您早前就尝试过复现预训练部分。请问您当初是直接能使用bash reproduce/pretraining/pretrain.sh跑通吗还是碰到一些报错？

我这里是从raise ValueError('cannot call `vectorize` on size 0 inputs '开始一直都有新的各种报错，数据读取部分不知道是因为库版本问题还是代码就是需要自己进行修改才能跑通。

如有答复提前感谢Gong博，谢谢！
