### ISSUE TITLE
Help of Reproducing

### ISSUE THREAD

**Issue by EuropeanGovernor** [moment-timeseries-foundation-model/moment-research#12]
Could you provide the checkpoint which can be used for reproducing? Thank you

**Comment by mononitogoswami** [comment]
Hi, 
Thanks for your interest in MOMENT. The pre-trained versions of MOMENT are available [here](https://huggingface.co/AutonLab)!

Best,
Mononito

**Comment by EuropeanGovernor** [comment]
@mononitogoswami  Sorry, I mean that HuggingFace provides Safetensor while the reproducing codes need .ckpt, could you provide the checkpoint in the form of .ckpt ? @
