### ISSUE TITLE
ask for moment_checkpoints files

### ISSUE THREAD

**Issue by gaoyi12138** [moment-timeseries-foundation-model/moment-research#2]
Hello author, due to my computer's insufficient configuration, the pre-training is very slow. Could you please share the moment_checkpoints files with me? Thank you very much!

**Comment by mononitogoswami** [comment]
Hi, 
Thanks for your interest in MOMENT! MOMENT-Large weights are publicly available on HuggingFace: https://huggingface.co/AutonLab/MOMENT-1-large

Let us know if you have any more questions!

Best,
Mononito
