### ISSUE TITLE
about reproduce the experiment

### ISSUE THREAD

**Issue by ooooooover** [moment-timeseries-foundation-model/moment-research#6]
Hello I would like to know how to reproduce the experiment on the WEATHER dataset. I'm trying to run pretrain_model/moment-research-main/reproduce/finetuning/forecasting_weather.sh directly but it says moment-research-main/results/moment_ checkpoints is empty, do I need to pretrain first or can I just call the model on huggingface to train it?

**Comment by mononitogoswami** [comment]
Hi, 
Thanks for your interest in MOMENT! You might have to change the script a little to load a pre-trained model. At the time of writing the code, we had MOMENT models stored in the `moment_checkpoint` directory locally. But you should certainly be able to use pre-trained MOMENT models and with minor changes to the script you should be able to run experiments. 

Best,
Mononito
