### ISSUE TITLE
Request for checkpoints for baselines in zero-shot experiments

### ISSUE THREAD

**Issue by soupeeli** [moment-timeseries-foundation-model/moment-research#7]
Hello! Thank you so much for the great work and repo! I was trying to reproduce the zero-shot experiment on both moment and baselines (like TimesNet and GPT4TS in Table 3 in the paper), and I would like to inquire if you could also provide the checkpoints for these baselines or if I need to run the script to get these checkpoints by myself? Thank you very much!

**Comment by mononitogoswami** [comment]
Hi,
Thanks for your interest in MOMENT. We ran those training runs, so I would recommend running GPT4TS and TimesNet using our scripts. 

Best,
Mononito
